---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-screenscraper-secrets
  namespace: homelab
spec:
  encryptedData:
    SCREENSCRAPER_PASSWORD: AgAmBzZa++u+0s6RT713XP4dM3IelFzJuwmRfMAy1J7DJ2WjBuEPURiWEJrKYXEJAPlJs3efouObnKPkKE3Rm5FHPsQGF8uai6t3g2Trz11B5DIHEXXgS4UfUTKIPSAedW7uXlwUV+BI+nhC4uWH6trBXTQqBBztrH7YJwCY01QTYiLv9cRki4RXHVyhQYHPKfa9dLnk1+BxYXQadVcXQDyPfmQ/dGQcoAEYBOisCBex0nxxzTW/TtRBqCDk9U1nHg1QWyaN49gPtpGFQBSVeXDvtPPu4tSPMHX1r321cl1+PzhkCJG65q9rJ6leU3grVqZDWg/yBwO4I7PW8+1aRCJeH77gR0/7vA1Au8HpJp0Omtiaxn9pBuzxjtY9KeFkeO2gFAkvw2IsPAP+u/36u575V5Vn31QhtrSPuv5ahqfNAixGmDtJXxfLdF2w6Kv8WfQ5EeHtotczkwPnanjiJ9C0KnTlt4/QA9MeFKfCw1ipPZBQzOTj32Rn2VMBu+RLQnuPre3FBmv5V98WaGYQ7X4isSYMNazsrWknS7lx+jxRuvwsi4iMiw45aUkp4o8iy3qkmH8PEmz8e3rSnMWZW0IcoB18WJSMzbjlfUtd6ETSV4sVCxLjASDJmyN85tktViwqS7N0558nLLIeyuWs5wjmw6fE4S0dMibUa3ldlcPtCbLUIYb0aPdswBy2fVz9lzz6+K/6hlziFE13Gka4XQ==
    SCREENSCRAPER_USER: AgAZS+TV0MzMXN4rZYHb5JNzRDq4nDvQbLiEtGIcDgIu8wbTlku42w8QAgPE1VH4H7gOwWM0N2bIjSngZEu3ClgJiQZ2gd6bTNR7CZ7aTuUvTIfxuB0Wu9JXud8Xzp3pU0au1vWtFcjlUlY3L9zgCSvkUJOVnbdOtPsZhic90E22AvfgfTrLGIBjIuIaALDtfWYQevctLU/zjO8yk/MtezEQmR/9WV/zDfl+xGn/K5b+r6PoASrzTMwvfdcGV+vpIslwNBvGpwY3bdtMKHorzD96kHRDal+JDp4gx306BMu7qMvoYSq0ZO1JyC8NlwuCndZQRsG2JOV0yWtXt2YHk3kEUzomwYiCJdSQpUXGzm1DfANpIS/J/hXstHAb98KkdfTBs450DkqnaVBTPrzF3HnKLgHPZzuD/RTK1fsaxeUwsvdU6W3+DYWCTobIFCoHnbjmXYhDqNWy2FI68kY1n3i6/fPOR5P+iC3pu++2wRNVIo4MsHFn6FID7SWR4yrkAc1Qv9mtXv4DO0U4CDhRTF8VZ1hcTLTx8OhjyUcO1sFrE8oJbjR3/LoEEDIECFXx1DVouLPQ3keidBC5uQfRPXblU8D6qmaXTb+4ApRD2TBkuqwFPzaOdmuW8yvn+a92VIdrHvlvuXvafXfbcozViVOS8QG8Ab9F0hPVTZxNYykH2blpjMag1ipFsmmzLfuMioegm9d19R3dh9pz31M=
  template:
    metadata:
      name: romm-screenscraper-secrets
      namespace: homelab
