---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-retroachievements-secrets
  namespace: homelab
spec:
  encryptedData:
    RETROACHIEVEMENTS_API_KEY: AgAH3z1BwZvCJfERSUi1rJ3YCAxCbK4+naJnpRt9Yy8rJELcX42Kjux8JfnFEFJV53BvwdwV37bjWZwyw0N9gKBOVoZlo3VsYkzjWcH2nhBl26OQOIFWZZ2CQ4BlQGfK4mhk5wdw2SaA+wEnYPevsVqvTjR2lWihoRPhcI+dKYbsQMDq3Wz1fVc6oCBR9MXvLt6Uqt/K0zB38JsTZ2NJHGz7gIRimE2bIIvLRiVQeqCmsk8SRHg1FSJtRtwP1u9XiEvp3oRkwsbBeei/hsPjzQoCf7HutEN3MwoTAstEctpnt1kimhfIBgymmpYcPXfGAyewG7THeUtvbJ31wI7O0srpryKVoxZL3JEUS1TTMH9BWV0H/iQUrD2vBjX2LDHhsmoihH6FWtbrfX511ngjwMapesnUZ43dfnd3Fbnh1yKNCMUnjYcYPbt/bhnemFTI1VMqZlJBj9byPg1/QCPWagfjJZYWkvY6deuyj/7qtShSnjxOKLPdm8AbpPghsZLUR+xUJQqyjWHDT/MZpecX7pr4/KguobZFGEJirMLnv07bMcLHEU4ckl9qlms6rjzBNkVYp44wwFPvXn0cV88s9Fp6VgEuv2KcCN0McqNlDTc3D9Or6N/gdPNYnsusQCCN3ROQyKEQeiK90UC3JcMoB0bwGwStws0bsVhNzgbLCIT3lCKKFaVgjniIJCki3vEb25o8TTpvzLWEJrwlN6Twnk8sZOfxaxzcqpPJc4uasi+ofA==
  template:
    metadata:
      name: romm-retroachievements-secrets
      namespace: homelab
