---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-retroachievements-secrets
  namespace: homelab
spec:
  encryptedData:
    RETROACHIEVEMENTS_API_KEY: AgCW9iVx75OOZkD21QDp4lxNWCgO1RjQ9SDX3hVkWmBK4LygtzjR0yfnkqVnjbuxIwS1DEwIQAhQ+Nv1YvS8mw0BWpiONAfohBMJCZZvotNaOxAWxD3hjdrQEH9ZOuciSmrUxPEnbmjGsfjIGt1P0UeUUMJMlqE9Tj5xTopBFcqVyudD2awcScvqSzGYRi+OWQtumseZP2usor2PLLKyfrw9oqCkgMRF/v1uRcQRzlm6TAF2Lxl7DNYAjoUqiezq3vuzVuIaqih9hzm7djQQ1yK4lQ73N32APFUDVSESI4+L/hp3gqqu6ob+wOUom+q5uh5sNN6HIKORYDXZ5ZavNZLpAJRuP7DcPt8cc9G+aSIkaEWra74pA+e8cC8XPtYSaBkahEONMH1zaF7iiHQeq8NKyOubOsgwaCTwh7NB/er+HBbAfuhQAeX+jMvUmp4dN9At7pVtInyQe3Idl0PfMJr3Z9PMIWz6PdqAY1lwetOQkCiLBCplZNs75RSDLVvkJ3stxftShZalh4wbhYmzJYvdmeN1JV4/59BmSskwcO4hj+XlwhBl01CmZsg6bu0xT9iz4xOyWRcVKDQYlj3eA59SjzGod5rutllZWH2VfbbpyP0MIJbgXyEvU/gdD7CVUMv9/UsYG4Mbm5jBEf947IfPVgHKx5sjDhXkQlHkgbOR/oirVOI0Hh+BE54WGD0YOXYVB3D4IbBnMoYiBJ9/+doNFH22UZY+evDtZ+DCnN20PxPBfYkwXTYFYhcFosbDZmrRtULtrlQNwYgboExNN7bRGy0VRLGNSHGjjrM0HTBpXEsZFXYyaOpt6cvVnfBlckmFeYsyEMGbz04kVlWwzhHI6mcs0CJD8BaAbBFMAbO2Ug==
  template:
    metadata:
      name: romm-retroachievements-secrets
      namespace: homelab
