---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-retroachievements-secrets
  namespace: homelab
spec:
  encryptedData:
    RETROACHIEVEMENTS_API_KEY: AgAPHEO664InjjbUcEBOIYksYOPfprzwGY4XmeHkT+EtjalmL2Kgz7ggRRAAVFNLGrLByZqEXBXMnl0d7G7AN11ESun48cnRauJqxkrFwUqNUD8Rz4BdxTcDFQwbMlBHuNxdBGx8+ambcx1lqwU8co3JRg3O/1odxnlcUIqLlftiCIMNeiucHX9gjisXdPgFTDrwEJfq999f6fxwV7VLc0SYOpLWiL0Vn+75NliwpKTnPAyk0LZDsbBT9c/JZG35TQtpIVjXfrF32fWRd5KUCGcT7XHKb79SvhbOfQkzNlNztiHzZ51l4VBjzYZ0R1l3io/4YGpKlgdrksnUUzz4Y+jzDu2B8Fv77gNYDK8zsTwTYYON94P0ZGDI/qMHnLGVRxrpgFNu/6ukRcmQys36FFc/S8Kn4gW95DgtByfk915JwEYw8Omz7xzziyMtd6usDrrj4ERaON/JvlhQmcVlRgzPnRXqF/bMZgMCunHckT3t3h4co4NDMclE6dbLdVcauqUTwvWRh9gC9SY4UP/Xxt80kggznP7UhzhKwwzO5fg7dhqtYQRJLbUoBpU2rwvbOECzXgwwDGDjVwVHQ/pmGY9Ye3ifqZSlbOQylat8n1noLCfnC6wb5QlAgjmJ7qUyc5ujd8uDIoR1T56xyArz8mrFjK3AbzA9U9cU/GaEfU6hMEi+9FgBImx+vWD6CaorDjC3sJO4AQueyZ5ENNyWPsNfsTU0KiuQ4kTXwMdtezWfKzlY/0c9dujdz79s6pC7s8d6IFHJiOLER5j4FLrgVwPGR8yrCa9TlMUFTLQj6kzTPbXrxPV3c8LxdI9mJY+GqwA=
  template:
    metadata:
      name: romm-retroachievements-secrets
      namespace: homelab
