---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-secrets
  namespace: homelab
spec:
  encryptedData:
    DB_PASSWORD: AgAASBSI1ZDSasukVEFLoqYTSixOWpST0zqxTaw7f670GIwPdSAKA4muG58VGieHq8/ftuab9S6J9+/FUM7EdBj7kCeRwsVpSkh6oe4L808cvSlHpd6MWFxrcsotd5G5HSfyftg6ScGXr1aAqYA9wwGDzzZ7Pxr4v4houCaqvXlIx4WwBTZXX2BceGeobqedq2xOj3HuMnLJNzfPJ+8XCnFUiyWdlHAHeK/dKHhFtfmIguVc+bY3G0MY+Xhp60qux3CEr8ejB+VY1/tjbqpJKLfvSyTiDo/FdRFyDQusmU30SfyNWUPZzaef+8FVqpRYyWsBN672x4gTqa9CsVWeTgAar0Zum2+6dTVGWtwSvOLv2TPuXHykJhR9+buRwKA/TU8/4zFHkWwxSMVIsGtGxTW7ybohAOItxG7a/xcALDhHOs+ji7ne+1SCOl+KbxnNemDSsxlkIQ/Ch4EyDnhrihdWt6vVf0KI4ZMhm1iLce+sJR/uUtRHx8boxtbMwt+tQBEVaLZm5N7eytjThJWKKzm6OjzSPMUIET82i6GzTETBSbRxRngls6BPYHAecrhrcMUF8q3YhJrzM7CL73l8Y6S57mzHidozytSVIEr5K7aGCVVNqImJc0mERLtlcNtNvj6UbklBdv9ZIqKGCMT9fMs0Cw3I5HUFgCcJe0sj+dBRA9vZLtFomipTAJ7Rg1Czvcw78/009cLD7swCZUBqGX5xe8bK9ztRU+UQJY3CwR/UTJpqg99nSJR8Ld4S7kBpliI=
  template:
    metadata:
      name: vikunja-secrets
      namespace: homelab
