---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-steamgriddb-secrets
  namespace: homelab
spec:
  encryptedData:
    STEAMGRIDDB_API_KEY: AgA3TUgMc/ZpQPLDRxo9xCs2K18Y6dgImZ6IJAjXJs3q2ZOSOLwh2GnHiJyhEQPKuJm/sK4gJveejeQ4o0RF9N69unwhRDpKbqlfKeGGRLJ3GqPkw/DylNxijZV+jXVLTRfghF5osCtpCjGgDFwpD0b6MKzdTrkCySZjZM8IKxc9cI4Hk1LTs0XDiZxB6DhJKX4wu26GW3y6OK9Sjz0ZJbArvOOtwHA+t5eEA0gFo1641OSbVVz3aBlTReOsmszVDT5CLZPK1DrxO2RRgK9m5YAG3VlMsYNVX+nRoS7/IetdiMY7d7NSngjgt+xg97UdyRVYqtmhhE3Y7FVhIdzC026oQjzVC++SSsfxPgyw+J8Pum1yasDWtgUyfRdQphXzf2dcYmS8eMCbUtSn4YzyHvl//4ua4CfWnwhx2JXdR6/dD9NpsGQgive8qR6e8cp57QVtlSpWZtmtLFHt93bosqgZApYEihsNyP5tnYY9knPNFWLwbjTrib6t9L4NIjJAb4lKOOloQGpfjIbL77qzG+ojig8O4vMpIHyrap6qzxjHmY/d7kNIzpFpY9IDHIvXn/xurtGERMUskSIEjG2puqPD8isQQDpMsJFM7YF7U3PJPQZJclbicKKLH6SOeveaiRdTv7TDitUOArAwcZ9XG1BYzFsSJ2ZjcarhDwgqW/jaa71nLOtYdD5hRdYNuR10us0VcNAda0vMsBbW1GK0p1TbzdRsV5vW3LuolkCOqNWq+g==
  template:
    metadata:
      name: romm-steamgriddb-secrets
      namespace: homelab
