---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pinchflat-secrets
  namespace: homelab
spec:
  encryptedData:
    BASIC_AUTH_PASSWORD: AgDezJzz8xxhIS9N7SCMpNBhQFlyN3CBhky4FKgJ6HZcOq/EjKrsEjLHZQU+H1sZvr+z750ofrttduC8K7/YkvUOD3/fJGLv6qCTDIT6Q5aOIZpkeWxTo7mWqHK+0um/I+2i0VLpd2oX/vpqZ8/M1pJHKhW56Ac4IjxU4k6P4a45402Yr6MQUuRYubv4D89NbwQL8OyX8JHx4LIW2DJleTSV94hfsg3iEtt2sNI3QdVlTIU7cRTjUjGfUiErIICOzVKmv2Up7EgrQGd0Vn0Ja2n8f7nGHM8tcjsAe+vgmZgdpwMf4dZsnOVTefUYex/GnxDfvt3/aI5UUGGu5lHss3ajBWmN8VBgYomaWD7s3RVdSU84Gjvni49ZTT7KWRQi6sp32/+tzzP1NwWTz7FncUmFUMWg3vprCBJ0C+SjG6gx78bJB+WstDgwQoslLlneoXoVoYSxJxB7qdwbV9ThR0UAGsxCTiK7fybRi9D3YJgZh6d24U2JdSOfjpq87jOPJdfl6+06h/2QC4uG+L+6cOyXzLtqVeH6G8BVyd3NHoz9DP3i2ToCwLbIcZt00DadvrdcAGEk/zDVa8asoHwlk9u9GjCPiKMwtvrAFklzZ0qTFZut4QsWnZTYIHPG4TJYs9ECpSmTC6p8egs2LffAkOKGn0xOOMOmm8hH3S4Foeg0O0C/I2jEh668FvHE9DAspjk9CTsv7SO5P5EY1zhXXKGJSUnPb7/GWiwqJRmR7+auCjoSwfbYppsW
    BASIC_AUTH_USERNAME: AgAdZh8m1ZtlD3Twsy0Bm2MU1MG85FJXtDzDaFUpb/FWCSYGI6brpd+aloB5mHWCwMjX1nUy8F9YnfsIl+S8yWPKQuHD2TVPA94H0pL/R56VzfUZtUOZ874hDHkU469a7q51BG3ihYrNdenCFHAq0fG9yuYPuP8MCJh04O2VSlCpsGGZdnTHl0YLSykV4gdjoHK27ylT7CTc9SomCVcRFKj1JtxMkx9C7yTouklEr0RhBhgNgZLt/4HdLG8+iwQT9N3ILOnglcY3mwZ3n1B8yKojstlKMgv86qG3kOgLL5W3nedhV65n3mzYGqVNFOthr0Hhs70HOYIC9IYVY7gdOjZfLRR+CuPjGicmAm+tkGrWIKO+CSlzg8vq7cbKNNxN9jAJEDvM3C50Gl+gjFiLO0+TJLKNZiCRkxuFaf2a1OiN01wuULnY4TXFdi2XPARtSUNVlM/ZK48bCw7kjIzU1L9FMyRnBKZBCce9jTmpxMQtIxrvjSCaMz3RWnIyyybJ8uhol3oKROPoh9NMiTREapbwUF1y2akrc16HZyXNx5SEp5H8YzH+3yKfTB/AE5IyKPuYgZmH7zUYj7h3yUhMIBQs5M1P0TMIqNt8mX/Btx98ZAJ87Avrj27s1jEtbSbyFfJ/G4Yxzakovps/0fFOqkEh/LblnsyJSvZKOiUCavS9/twRXWehb0pm9EEldbjjJn+hOSupmw==
  template:
    metadata:
      name: pinchflat-secrets
      namespace: homelab
