apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Base e segredos
  - 000-namespace.yaml
  - 100-sealed-secrets.yaml
  - 110-romm-screenscraper-sealed-secret.yaml
  - 120-romm-retroachievements-sealed-secret.yaml
  - 130-romm-steamgriddb-sealed-secret.yaml
  - 140-vikunja-sealed-secret.yaml
  - 150-n8n-sealed-secret.yaml
  - 155-pinchflat-sealed-secret.yaml

  # Certificados
  - 200-certificates.yaml
  - 210-argocd-certificate.yaml

  # Serviços e aplicações
  - 300-portainer.yaml
  - 310-nextcloud.yaml
  - 320-gitea.yaml
  - 330-navidrome.yaml
  - 340-ingress.yaml
  - 350-kavita.yaml
  - 360-jellyfin.yaml
  - 370-radarr-bazarr.yaml
  - 380-homepage.yaml
  - 390-pod-cleanup-cronjob.yaml
  - 400-immich.yaml
  - 410-memos.yaml
  - 420-romm.yaml
  - 430-vikunja.yaml
  - 440-n8n.yaml
  - 450-actual-budget.yaml
  - 460-home-assistant.yaml
  - 465-pinchflat.yaml

  # GitOps
  - 901-argocd-applications.yaml
